

(*RunFeature "LoginNopcommerce"

to handle The_application_launches_on_the_chrome_browser
	typetext windowsKey , "r"
	typetext "chrome" && "https:\\demo.nopcommerce.com\" &&"--start --maximize", return
	waitfor 20 , text:"Welcome to our store"
end The_application_launches_on_the_chrome_browser



to handle Login_option_is_avilable
	if imagefound(text:"Log in",caseSensitive:yes) 
	then 
		click FoundImageLocation()
	else
		log "You have already logged in"
	end if
end Login_option_is_avilable

(*to handle click_on_the_login_option
	//pass
end click_on_the_login_option*)

to handle Enter_Email_address
	waitfor 20,text:"Email"
	click text:"Email"
	typetext "Sample@123.com"
end Enter_Email_address

to handle Enter_password
	waitfor 20,text:"Password"
	click text:"password"
	typetext"Welcome@123"
end Enter_password

to handle click_on_Login_button
	click text:"LOG IN",casesensitve:yes
end click_on_Login_button


to LogSuccessMessage
	log "Successfully logged in to Nopcommerce"
end LogSuccessMessage*)

log Learnhanlders()

function Learnhanlders
	log "command"

	return "Fun"
end Learnhanlders


